# Generated by Django 4.1 on 2022-10-16 23:19

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', ckeditor.fields.RichTextField()),
                ('creacion', models.DateTimeField(auto_now=True)),
                ('de', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='de', to=settings.AUTH_USER_MODEL)),
                ('para', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='para', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
